### ISSUE TITLE
Create hello world nextjs project

### ISSUE THREAD

**Issue by Gbaja** [BridgeMap/bridgemap-v1#4]
### Background

We decided on using nextJS to build the project. We need to create a basic next js 

### Subtask

- [ ] Using the create-next-app command, create a next JS app
- [ ] Remove any components/files that you think we won't use. 
- [ ] It should render the text "BridgeMap" in big bold text
- [ ] Update readme with clear instructions on how to work with the repo
- [ ] Push to the bridgemap-v1 repository on github
