### ISSUE TITLE
Deploy basic nextjs project

### ISSUE THREAD

**Issue by Gbaja** [BridgeMap/bridgemap-v1#5]
### Background

We decided on using netflify to deploy our project

### Subtask

- [ ] Make a netflify account using the Bridgemap gmail account and password
- [ ] Deploy the basic nextJS project created in this [ticket](https://github.com/BridgeMap/bridgemap-v1/issues/4)
- [ ] Use the generic auto generated url netlify has for now
