### ISSUE TITLE
Connect nextjs app with google sheet

### ISSUE THREAD

**Issue by Gbaja** [BridgeMap/bridgemap-v1#6]
### Background

We decided to use google sheet for our data storage

### Subtask

- [ ] Create a google form in the BridgeMap gmail folder. This is the form we will be sending out to organisations. There might be one that exists already
- [ ] From the form create a google sheet
- [ ] Hook up nextJS to read data from the google sheet. 
- [ ] Query the data so that it fetches during build on netflify

Useful links
- [ ] https://andreaskeller.name/blog/nextjs-google-sheets-cms
- [ ] https://dev.to/frasnym/connecting-your-nextjs-mini-project-with-google-spreadsheets-as-database-1o2d
- [ ] https://www.netlify.com/blog/2020/12/16/query-an-api-at-both-build-time-and-runtime-with-next.js/
